// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

#pragma once

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

// The following structs are used to implement the lowest level
// of the FFI, and thus useful to multiple uniffied crates.
// We ensure they are declared exactly once, with a header guard, UNIFFI_SHARED_H.
#ifdef UNIFFI_SHARED_H
    // We also try to prevent mixing versions of shared uniffi header structs.
    // If you add anything to the #else block, you must increment the version suffix in UNIFFI_SHARED_HEADER_V4
    #ifndef UNIFFI_SHARED_HEADER_V4
        #error Combining helper code from multiple versions of uniffi is not supported
    #endif // ndef UNIFFI_SHARED_HEADER_V4
#else
#define UNIFFI_SHARED_H
#define UNIFFI_SHARED_HEADER_V4
// ⚠️ Attention: If you change this #else block (ending in `#endif // def UNIFFI_SHARED_H`) you *must* ⚠️
// ⚠️ increment the version suffix in all instances of UNIFFI_SHARED_HEADER_V4 in this file.           ⚠️

typedef struct RustBuffer
{
    int32_t capacity;
    int32_t len;
    uint8_t *_Nullable data;
} RustBuffer;

typedef int32_t (*ForeignCallback)(uint64_t, int32_t, const uint8_t *_Nonnull, int32_t, RustBuffer *_Nonnull);

typedef struct ForeignBytes
{
    int32_t len;
    const uint8_t *_Nullable data;
} ForeignBytes;

// Error definitions
typedef struct RustCallStatus {
    int8_t code;
    RustBuffer errorBuf;
} RustCallStatus;

// ⚠️ Attention: If you change this #else block (ending in `#endif // def UNIFFI_SHARED_H`) you *must* ⚠️
// ⚠️ increment the version suffix in all instances of UNIFFI_SHARED_HEADER_V4 in this file.           ⚠️
#endif // def UNIFFI_SHARED_H

// Continuation callback for UniFFI Futures
typedef void (*UniFfiRustFutureContinuation)(void * _Nonnull, int8_t);

// Scaffolding functions
void*_Nonnull uniffi_pubky_fn_clone_keyprovider(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
void uniffi_pubky_fn_free_keyprovider(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
void uniffi_pubky_fn_init_callback_keyprovider(ForeignCallback _Nonnull handle
);
RustBuffer uniffi_pubky_fn_method_keyprovider_secret_key(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
void*_Nonnull uniffi_pubky_fn_clone_pubkysession(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
void uniffi_pubky_fn_free_pubkysession(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
RustBuffer uniffi_pubky_fn_method_pubkysession_info(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
void uniffi_pubky_fn_method_pubkysession_signout(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
void*_Nonnull uniffi_pubky_fn_method_pubkysession_storage(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
void*_Nonnull uniffi_pubky_fn_clone_publicstorage(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
void uniffi_pubky_fn_free_publicstorage(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
RustBuffer uniffi_pubky_fn_method_publicstorage_get(void*_Nonnull ptr, RustBuffer uri, RustCallStatus *_Nonnull out_status
);
RustBuffer uniffi_pubky_fn_method_publicstorage_list(void*_Nonnull ptr, RustBuffer uri, RustCallStatus *_Nonnull out_status
);
void*_Nonnull uniffi_pubky_fn_clone_sdk(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
void uniffi_pubky_fn_free_sdk(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
void*_Nonnull uniffi_pubky_fn_constructor_sdk_new(RustCallStatus *_Nonnull out_status
    
);
void*_Nonnull uniffi_pubky_fn_method_sdk_await_approval(void*_Nonnull ptr, RustBuffer request_id, RustCallStatus *_Nonnull out_status
);
void*_Nonnull uniffi_pubky_fn_method_sdk_public_storage(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
void*_Nonnull uniffi_pubky_fn_method_sdk_signin(void*_Nonnull ptr, void*_Nonnull key_provider, RustBuffer homeserver, RustCallStatus *_Nonnull out_status
);
void*_Nonnull uniffi_pubky_fn_method_sdk_signup(void*_Nonnull ptr, void*_Nonnull key_provider, RustBuffer homeserver, RustBuffer options, RustCallStatus *_Nonnull out_status
);
RustBuffer uniffi_pubky_fn_method_sdk_start_auth_flow(void*_Nonnull ptr, RustBuffer capabilities, RustCallStatus *_Nonnull out_status
);
void*_Nonnull uniffi_pubky_fn_clone_sessionstorage(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
void uniffi_pubky_fn_free_sessionstorage(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
void uniffi_pubky_fn_method_sessionstorage_delete(void*_Nonnull ptr, RustBuffer path, RustCallStatus *_Nonnull out_status
);
RustBuffer uniffi_pubky_fn_method_sessionstorage_get(void*_Nonnull ptr, RustBuffer path, RustCallStatus *_Nonnull out_status
);
RustBuffer uniffi_pubky_fn_method_sessionstorage_list(void*_Nonnull ptr, RustBuffer path, RustCallStatus *_Nonnull out_status
);
void uniffi_pubky_fn_method_sessionstorage_put(void*_Nonnull ptr, RustBuffer path, RustBuffer content, RustCallStatus *_Nonnull out_status
);
RustBuffer ffi_pubky_rustbuffer_alloc(int32_t size, RustCallStatus *_Nonnull out_status
);
RustBuffer ffi_pubky_rustbuffer_from_bytes(ForeignBytes bytes, RustCallStatus *_Nonnull out_status
);
void ffi_pubky_rustbuffer_free(RustBuffer buf, RustCallStatus *_Nonnull out_status
);
RustBuffer ffi_pubky_rustbuffer_reserve(RustBuffer buf, int32_t additional, RustCallStatus *_Nonnull out_status
);
void ffi_pubky_rust_future_poll_u8(void* _Nonnull handle, UniFfiRustFutureContinuation _Nonnull callback, void* _Nonnull callback_data
);
void ffi_pubky_rust_future_cancel_u8(void* _Nonnull handle
);
void ffi_pubky_rust_future_free_u8(void* _Nonnull handle
);
uint8_t ffi_pubky_rust_future_complete_u8(void* _Nonnull handle, RustCallStatus *_Nonnull out_status
);
void ffi_pubky_rust_future_poll_i8(void* _Nonnull handle, UniFfiRustFutureContinuation _Nonnull callback, void* _Nonnull callback_data
);
void ffi_pubky_rust_future_cancel_i8(void* _Nonnull handle
);
void ffi_pubky_rust_future_free_i8(void* _Nonnull handle
);
int8_t ffi_pubky_rust_future_complete_i8(void* _Nonnull handle, RustCallStatus *_Nonnull out_status
);
void ffi_pubky_rust_future_poll_u16(void* _Nonnull handle, UniFfiRustFutureContinuation _Nonnull callback, void* _Nonnull callback_data
);
void ffi_pubky_rust_future_cancel_u16(void* _Nonnull handle
);
void ffi_pubky_rust_future_free_u16(void* _Nonnull handle
);
uint16_t ffi_pubky_rust_future_complete_u16(void* _Nonnull handle, RustCallStatus *_Nonnull out_status
);
void ffi_pubky_rust_future_poll_i16(void* _Nonnull handle, UniFfiRustFutureContinuation _Nonnull callback, void* _Nonnull callback_data
);
void ffi_pubky_rust_future_cancel_i16(void* _Nonnull handle
);
void ffi_pubky_rust_future_free_i16(void* _Nonnull handle
);
int16_t ffi_pubky_rust_future_complete_i16(void* _Nonnull handle, RustCallStatus *_Nonnull out_status
);
void ffi_pubky_rust_future_poll_u32(void* _Nonnull handle, UniFfiRustFutureContinuation _Nonnull callback, void* _Nonnull callback_data
);
void ffi_pubky_rust_future_cancel_u32(void* _Nonnull handle
);
void ffi_pubky_rust_future_free_u32(void* _Nonnull handle
);
uint32_t ffi_pubky_rust_future_complete_u32(void* _Nonnull handle, RustCallStatus *_Nonnull out_status
);
void ffi_pubky_rust_future_poll_i32(void* _Nonnull handle, UniFfiRustFutureContinuation _Nonnull callback, void* _Nonnull callback_data
);
void ffi_pubky_rust_future_cancel_i32(void* _Nonnull handle
);
void ffi_pubky_rust_future_free_i32(void* _Nonnull handle
);
int32_t ffi_pubky_rust_future_complete_i32(void* _Nonnull handle, RustCallStatus *_Nonnull out_status
);
void ffi_pubky_rust_future_poll_u64(void* _Nonnull handle, UniFfiRustFutureContinuation _Nonnull callback, void* _Nonnull callback_data
);
void ffi_pubky_rust_future_cancel_u64(void* _Nonnull handle
);
void ffi_pubky_rust_future_free_u64(void* _Nonnull handle
);
uint64_t ffi_pubky_rust_future_complete_u64(void* _Nonnull handle, RustCallStatus *_Nonnull out_status
);
void ffi_pubky_rust_future_poll_i64(void* _Nonnull handle, UniFfiRustFutureContinuation _Nonnull callback, void* _Nonnull callback_data
);
void ffi_pubky_rust_future_cancel_i64(void* _Nonnull handle
);
void ffi_pubky_rust_future_free_i64(void* _Nonnull handle
);
int64_t ffi_pubky_rust_future_complete_i64(void* _Nonnull handle, RustCallStatus *_Nonnull out_status
);
void ffi_pubky_rust_future_poll_f32(void* _Nonnull handle, UniFfiRustFutureContinuation _Nonnull callback, void* _Nonnull callback_data
);
void ffi_pubky_rust_future_cancel_f32(void* _Nonnull handle
);
void ffi_pubky_rust_future_free_f32(void* _Nonnull handle
);
float ffi_pubky_rust_future_complete_f32(void* _Nonnull handle, RustCallStatus *_Nonnull out_status
);
void ffi_pubky_rust_future_poll_f64(void* _Nonnull handle, UniFfiRustFutureContinuation _Nonnull callback, void* _Nonnull callback_data
);
void ffi_pubky_rust_future_cancel_f64(void* _Nonnull handle
);
void ffi_pubky_rust_future_free_f64(void* _Nonnull handle
);
double ffi_pubky_rust_future_complete_f64(void* _Nonnull handle, RustCallStatus *_Nonnull out_status
);
void ffi_pubky_rust_future_poll_pointer(void* _Nonnull handle, UniFfiRustFutureContinuation _Nonnull callback, void* _Nonnull callback_data
);
void ffi_pubky_rust_future_cancel_pointer(void* _Nonnull handle
);
void ffi_pubky_rust_future_free_pointer(void* _Nonnull handle
);
void*_Nonnull ffi_pubky_rust_future_complete_pointer(void* _Nonnull handle, RustCallStatus *_Nonnull out_status
);
void ffi_pubky_rust_future_poll_rust_buffer(void* _Nonnull handle, UniFfiRustFutureContinuation _Nonnull callback, void* _Nonnull callback_data
);
void ffi_pubky_rust_future_cancel_rust_buffer(void* _Nonnull handle
);
void ffi_pubky_rust_future_free_rust_buffer(void* _Nonnull handle
);
RustBuffer ffi_pubky_rust_future_complete_rust_buffer(void* _Nonnull handle, RustCallStatus *_Nonnull out_status
);
void ffi_pubky_rust_future_poll_void(void* _Nonnull handle, UniFfiRustFutureContinuation _Nonnull callback, void* _Nonnull callback_data
);
void ffi_pubky_rust_future_cancel_void(void* _Nonnull handle
);
void ffi_pubky_rust_future_free_void(void* _Nonnull handle
);
void ffi_pubky_rust_future_complete_void(void* _Nonnull handle, RustCallStatus *_Nonnull out_status
);
uint16_t uniffi_pubky_checksum_method_keyprovider_secret_key(void
    
);
uint16_t uniffi_pubky_checksum_method_pubkysession_info(void
    
);
uint16_t uniffi_pubky_checksum_method_pubkysession_signout(void
    
);
uint16_t uniffi_pubky_checksum_method_pubkysession_storage(void
    
);
uint16_t uniffi_pubky_checksum_method_publicstorage_get(void
    
);
uint16_t uniffi_pubky_checksum_method_publicstorage_list(void
    
);
uint16_t uniffi_pubky_checksum_method_sdk_await_approval(void
    
);
uint16_t uniffi_pubky_checksum_method_sdk_public_storage(void
    
);
uint16_t uniffi_pubky_checksum_method_sdk_signin(void
    
);
uint16_t uniffi_pubky_checksum_method_sdk_signup(void
    
);
uint16_t uniffi_pubky_checksum_method_sdk_start_auth_flow(void
    
);
uint16_t uniffi_pubky_checksum_method_sessionstorage_delete(void
    
);
uint16_t uniffi_pubky_checksum_method_sessionstorage_get(void
    
);
uint16_t uniffi_pubky_checksum_method_sessionstorage_list(void
    
);
uint16_t uniffi_pubky_checksum_method_sessionstorage_put(void
    
);
uint16_t uniffi_pubky_checksum_constructor_sdk_new(void
    
);
uint32_t ffi_pubky_uniffi_contract_version(void
    
);

